apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: knativecon-issues
spec:
  eventTypes:
    - issues
    - issue_comment
  ownerAndRepository: knativecon/demo22
  accessToken:
    secretKeyRef:
      name: github-secret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: github-secret
      key: secretToken
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-crsx-discussions
